### ISSUE TITLE
Not working in 5.1.1

### ISSUE THREAD

**Issue by regystro** [lwis/ConnectToNetworksWithNoConnection#1]
Hi.

Tested on Nexus 4 stock rom 5.1.1 and seems not to work.
Couldn't test it on 5.1.0.

Thank you.

**Comment by lwis** [comment]
I wrote this before Xposed was ported to 5.1, so it's entirely possible
that it doesn't work. If you could provide me with an Xposed log, I'll be
able to take a look!

**Comment by regystro** [comment]
Here you are:

    06-12 12:13:24.374 I/Xposed  (  197): -----------------
    06-12 12:13:24.374 I/Xposed  (  197): Starting Xposed binary version 61, compiled for SDK 22
    06-12 12:13:24.374 I/Xposed  (  197): Device: Nexus 4 (LGE), Android version 5.1.1 (SDK 22)
    06-12 12:13:24.374 I/Xposed  (  197): ROM: LMY47V
    06-12 12:13:24.374 I/Xposed  (  197): Build fingerprint: google/occam/mako:5.1.1/LMY47V/1836172:user/release-keys
    06-12 12:13:24.374 I/Xposed  (  197): Platform: armeabi-v7a, 32-bit binary, system server: yes
    06-12 12:13:24.374 I/Xposed  (  197): SELinux enabled: yes, enforcing: yes
    06-12 12:13:25.795 I/Xposed  (  197): -----------------
    06-12 12:13:25.797 I/Xposed  (  197): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
    06-12 12:13:26.507 I/Xposed  (  197): Detected ART runtime
    06-12 12:13:26.569 I/Xposed  (  197): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
    06-12 12:13:26.834 I/Xposed  (  197): Initializing XposedBridge version 64
    06-12 12:13:27.035 I/Xposed  (  197): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
    06-12 12:13:27.468 I/Xposed  (  197):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
    06-12 12:13:27.536 I/Xposed  (  197): Loading modules from /data/app/de.defim.apk.customshare-1/base.apk
    06-12 12:13:27.585 I/Xposed  (  197):   Loading class de.defim.apk.customshare.Xposed
    06-12 12:13:27.618 I/Xposed  (  197):     [CustomShare] initialized
    06-12 12:13:27.618 I/Xposed  (  197):   Loading class de.defim.apk.customshare.Xcheck
    06-12 12:13:27.620 I/Xposed  (  197): Loading modules from /data/app/com.lewisjuggins.connecttonetworkswithnoconnection-1/base.apk
    06-12 12:13:27.639 I/Xposed  (  197):   Loading class com.lewisjuggins.connecttonetworkswithnoconnection.WifiMod
    06-12 12:13:27.665 I/Xposed  (  197): Loading modules from /data/app/com.ceco.lollipop.gravitybox-1/base.apk
    06-12 12:13:28.438 I/Xposed  (  197):   Loading class com.ceco.lollipop.gravitybox.GravityBox
    06-12 12:13:28.497 I/Xposed  (  197): GB:Hardware: mako
    06-12 12:13:28.497 I/Xposed  (  197): GB:Product: occam
    06-12 12:13:28.497 I/Xposed  (  197): GB:Device manufacturer: LGE
    06-12 12:13:28.497 I/Xposed  (  197): GB:Device brand: google
    06-12 12:13:28.498 I/Xposed  (  197): GB:Device model: Nexus 4
    06-12 12:13:28.507 I/Xposed  (  197): GB:Device type: phone
    06-12 12:13:28.508 I/Xposed  (  197): GB:Is MTK device: false
    06-12 12:13:28.508 I/Xposed  (  197): GB:Is Xperia device: false
    06-12 12:13:28.508 I/Xposed  (  197): GB:Is Moto XT device: false
    06-12 12:13:28.508 I/Xposed  (  197): GB:Has Lenovo custom UI: false
    06-12 12:13:28.509 I/Xposed  (  197): GB:Has telephony support: true
    06-12 12:13:28.511 I/Xposed  (  197): GB:Has Gemini support: false
    06-12 12:13:28.511 I/Xposed  (  197): GB:Android SDK: 22
    06-12 12:13:28.511 I/Xposed  (  197): GB:Android Release: 5.1.1
    06-12 12:13:28.511 I/Xposed  (  197): GB:ROM: LMY47V
    06-12 12:13:34.349 I/Xposed  (  608): Amplify: Version 3.0.9
    06-12 12:13:34.349 I/Xposed  (  608): Amplify: Attempting 19to21 AlarmHook
    06-12 12:13:34.351 I/Xposed  (  608): Amplify: Successful 19to21 AlarmHook
    06-12 12:13:34.351 I/Xposed  (  608): Amplify: Attempting 21 WakeLockHook
    06-12 12:13:34.353 I/Xposed  (  608): Amplify: Successful 21 WakeLockHook
    06-12 12:13:34.353 I/Xposed  (  608): Amplify: Service Blocking Status: true
    06-12 12:13:34.353 I/Xposed  (  608): Amplify: Attempting 17to20 ServiceHook
    06-12 12:13:34.359 I/Xposed  (  608): Amplify: Successful 17to20 ServiceHook
    06-12 12:17:34.981 I/XposedInstaller( 5348): Downloaded http://dl.xposed.info/repo/partial/4432.xml.gz with status 0 (error: null), size 65 bytes
    06-12 12:17:34.988 I/XposedInstaller( 5348): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 4432 (0 new / 0 removed modules)

**Comment by lwis** [comment]
It looks like my module loaded, how're you testing this?

**Comment by regystro** [comment]
I share my PC's WiFi connection as an hotspot access point. My Nexus 4 connects without any  problems, and it also has Internet access but for an unkown reason Android 5.1.1 stops connecting automatically claiming "no internet connection is available, I won't reconnect". I guess that your module is supposed to avoid this behaviour and tell the OS "don't worry if there's no internet connection, you can connect automatically to that SSID allways". Am I right? Well, that doesn't happen, and OS keeps blacklisting my SSID and I'm forced to click on the SSID to reconnect.

**Comment by lwis** [comment]
My module is very simple, I swap out the android.net.wifi.WifiConfiguration.hasNoInternetAccess() to always return 'false'. Not sure why that wouldn't work, there may be more to it than I initially anticipated upon looking at their changes.

**Comment by boettlerjeremy** [comment]
Need help rooting a rca 7 voyager 2 tablet.Kingroot said need high permision what can i do and  safely
